export interface User {
    id?: string;
    nome: string;
    ativo: number;
    cpf: string;
    rg: string | null;
    dataNasc: string;
    telefone: string;
    profissao: string | null;
    escolaridade: number;
    patologia: string;
    cep: string;
    municipio: string;
    bairro: string;
    rua: string;
    numero: string;
    referencia: string | null;
    respNome: string | null;
    respCpf: string | null;
    respIdade: number | null;
    respTelefone: string | null;
    respProfissao: string | null;
    respEscolaridade: number | null;
    respParentesco: string | null;
    respRenda: string | null;
    fonteRenda: string;
    valorRenda: number;
    moradia: string;
    agua: string;
    aguaValor: string;
    energia: string;
    energiaValor: string;
    bens: string;
    internet: boolean;
    cras: boolean;
    acessoCRAS: string;
    descDoenca: string;
    medicamentos: string;
    medicamentosGasto: number;
    tratamento: string;
    nutri: string;
    tempoTratamento: string;
    local: string;
    encaminhamento: string;
    solicitacoes: string;
    motivoDesligamento: string;
    parecerSocial: string;
}

export const escolaridades = ['Ensino Fundamental incompleto','Ensino Fundamental completo','Ensino Medio incompleto','Ensino Medio completo','Ensino Superior incompleto','Ensino Superior completo']
